version: '3.8'
services:
  client:
    image: alerty-prod
    container_name: alerty-prod
    build:
      context: ./client
      target: production
      dockerfile: Dockerfile
    ports:
      - '3000:3000'
    depends_on:
      - server

  server:
    image: alerty-server-prod
    build:
      context: ./server
      dockerfile: Dockerfile
    ports:
      - '8080:8080'
