version: '3.8'
services:
  client:
    image: alerty-dev
    container_name: alerty-dev
    build:
      context: ./client
      dockerfile: Dockerfile
      target: dev
    volumes:
      - .:/client
      - /client/node_modules
      - /client/.next
    ports:
      - '3000:3000'
    depends_on:
      - server

  server:
    image: alerty-server-dev
    container_name: alerty-server-dev
    build:
      context: ./server
      dockerfile: Dockerfile
      target: dev
    ports:
      - '8080:8080'
