version: '3.8'
services:
  client:
    image: alerty
    container_name: alerty
    build:
      context: ./client
      target: production
      dockerfile: Dockerfile
    volumes:
      - .:/client
      - /client/node_modules
      - /client/.next
    ports:
      - '3000:3000'
    depends_on:
      - server

  server:
    image: alerty-server
    build:
      context: ./server
      dockerfile: Dockerfile
    volumes:
      - .:/server
      - /server/node_modules
      - /server/dist
    ports: ['8080:8080']
